openteach/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from openteach import settings
from uploader import views

#if not settings.DEBUG:
#from haystack.forms import HighlightedSearchForm
#from haystack.views import SearchView

urlpatterns = [
	#url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('uploader.urls', namespace="uploader")),
    #url(r'^uploader/', include('uploader.urls', namespace="uploader")),
    #url(r'^$', views.index, name='index'),
]

#if not settings.DEBUG:
#additional_patterns = patterns(
#    url(r'^search/$', SearchView(form_class=HighlightedSearchForm)),
#)
#urlpatterns += additional_patterns 

uploader/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from uploader import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^denied/$', views.denied, name='denied'),
 
    url(r'^assignment/add/$', views.assignment, name='assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/$', views.view_assignment, name='view_assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/edit/$', views.assignment, name='assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/delete/$', views.delete_assignment, name='delete_assignment'),
    url(r'^assignment/(?P<assignment_code>[\w\d-]+)/mark/(?P<submission_id>[\d]+)/$', views.mark_assignment, name='mark_assignment'),
    url(r'^assignment/(?P<assignment_code>[\w\d-]+)/mark/(?P<absent>[\w]+)/(?P<student_id>[\d]+)', views.mark_assignment, name='mark_assignment'),
    
    url(r'^lookup/syllabus/(?P<subject_id>\d+)/$', views.get_syllabuses, name='get_syllabuses'),
    url(r'^lookup/unit/(?P<syllabus_id>\d+)/$', views.get_units, name='get_units'),
    url(r'^lookup/quick/(?P<type>[\w]+)/(?P<code>[\w\d]+)/$', views.get_object_from_code, name='get_object_from_code'),
    url(r'^lookup/unit_topic/(?P<unit_id>\d+)/$', views.get_unit_topics, name='get_unit_topics'),
    url(r'^lookup/url_description/$', views.get_url_description, name='get_url_description'),
    url(r'^bulk/bookmark/(?P<action>.+)/(?P<ids>.+)/$', views.bulk_bookmark_update, name='bulk_bookmark_update'),
    url(r'^pre-post/(?P<action>.+)/(?P<id>.+)/$', views.pre_post, name='pre_post'),
    
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^favourites/$', views.favourites, name='favourites'),
    url(r'^favourites/add-(?P<thing>[\w\d-]+)/(?P<slug>[\w\d-]+)$', views.add_favourite, name='add_favourite'),
    url(r'^favourites/remove-(?P<thing>[\w\d-]+)/(?P<slug>[\w\d-]+)$', views.remove_favourite, name='remove_favourite'),
    
    url(r'^resource/(?P<slug>[\w\d-]+)/$', views.view_resource, name='view_resource'),
    url(r'^resource/(?P<slug>[\w\d-]+)/embed/$', views.view_resource_embed, name='view_resource_embed'),
    url(r'^resource/(?P<slug>[\w\d-]+)/delete$', views.delete_resource, name='delete_resource'),
    url(r'^lesson/(?P<code>[\w\d-]+)/edit', views.edit_lesson, name='edit_lesson'),
    url(r'^lesson/(?P<code>[\w\d-]+)/delete', views.delete_lesson, name='delete_lesson'),
    url(r'^lesson/(?P<code>[\w\d-]+)/link', views.link_lesson, name='link_lesson'),
    url(r'^lesson/new/$', views.lesson_creator, name='lesson_creator'),
    url(r'^lesson_item/(?P<id>[\d-]+)/edit', views.edit_lesson_item, name='edit_lesson_item'),
    #url(r'^resource/(?P<slug>[\w\d-]+)/edit$', views.resource, name='resource'),
    
    url(r'^groups/$', views.groups_list, name='groups_list'),
    url(r'^groups/add/$', views.groups, name='groups'),
    url(r'^groups/(?P<slug>[\w\d-]+)/edit/$', views.groups, name='groups'),
    url(r'^group/(?P<slug>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/$', views.lesson, name='lesson'),
    url(r'^group/(?P<code>[\w\d-]+)/$', views.group, name='group'),
    url(r'^group/(?P<group_code>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/show/$', views.lesson_show, name='lesson_show'),
    url(r'^group/(?P<group_code>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/present/$', views.lesson_present, name='lesson_present'),
    
    # url(r'^bookmark/add/(?P<url>[-_./\w\d-]+)$', views.bookmark, name='bookmark'),
    url(r'^bookmark/add/', views.bookmark, name='bookmark'),
    url(r'^bookmark/link/(?P<slug>[\w\d-]+)/$', views.link_bookmark, name='link_bookmark'),
    # url(r'^bookmark/add/stage_two/$', views.link_resource, name='link_resource'),
    url(r'^bookmark/(?P<slug>[\w\d-]+)/edit/$', views.bookmark, name='bookmark'),
    url(r'^bookmark/(?P<slug>[\w\d-]+)/delete/$', views.delete_bookmark, name='delete_bookmark'),

    url(r'^file/add/$', views.file, name='file'),
    url(r'^file/add/stage_two/$', views.link_resource, name='link_resource'),
    url(r'^file/link/(?P<slug>[\w\d-]+)/$', views.link_file, name='link_file'),
    url(r'^file/(?P<slug>[\w\d-]+)/edit/$', views.file, name='file'),
    url(r'^file/(?P<slug>[\w\d-]+)/delete/$', views.delete_file, name='delete_file'),
    
    url(r'^user/profile/$', views.profile, name='profile'),
    url(r'^user/resources', views.user_resources, name='user_resources'),
    url(r'^user/files', views.user_files, name='user_files'),
    url(r'^user/bookmarks', views.user_bookmarks, name='user_bookmarks'),
    url(r'^user/questions', views.user_questions, name='user_questions'),
    url(r'^user/lessons', views.user_lessons, name='user_lessons'),
    url(r'^user/grading/add/', views.grading, name='grading'),
    url(r'^user/grading/', views.user_grading, name='user_grading'),
    url(r'^user/tests/', views.user_tests, name='user_tests'),
    url(r'^user/(?P<username>[\w\d-]+)/$', views.profile, name='profile'),
    
    url(r'lesson/(?P<slug>[\w\d-]+)/$', views.lesson, name='lesson'),

    
    url(r'^notes/(?P<code>[\w\d-]+)/$', views.view_notes_code, name='view_notes_code'),
    # url(r'^notes/(?P<slug>[\w\d-]+)/edit/$', views.notes_d, name='notes_d'),
    
    url(r'^students/signup/$', views.student_signup, name='student_signup'),
    url(r'^teachers/signup/$', views.teacher_signup, name='teacher_signup'),

    
    # url(r'^leaderboard', views.leaderboard, name='leaderboard'),
    
    url(r'^vote/(?P<content_type>[\w]+)/(?P<object_id>[\d]+)/(?P<vote>[\d])/$', views.vote, name='vote'),
    
    url(r'^licences', views.licences, name='licences'),
    
    url(r'^upload_image', views.upload_image, name='upload_image'),
    url(r'^image/(?P<image_id>\d+)/$', views.view_image, name='view_image'),
    
    url(r'^test/add', views.add_test, name='add_test'),
    url(r'^test/(?P<code>[\w\d-]+)/feedback', views.test_feedback, name='test_feedback'),
    url(r'^test/(?P<code>[\w\d-]+)/link', views.link_test, name='link_test'),
    url(r'^test/(?P<code>[\w\d-]+)', views.test, name='test'),

    
    url(r'^add-question/(?P<slug>[\w\d-]+)', views.question, name='question'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/resources$', views.topic_resources, name='topic_resources'),
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)$', views.topic, name='topic'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/$', views.category, name='category'),
    url(r'^(?P<subject_slug>[\w\d-]+)/$', views.subject, name='subject'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/notes/$', views.view_notes, name='view_notes'),
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/notes/edit$', views.notes, name='notes'),

    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.syllabus, name='syllabus'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/resources/$', views.syllabus_resources, name='syllabus_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/$', views.syllabuses, name='syllabuses'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.unit, name='unit'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/resources/$', views.unit_resources, name='unit_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/resources/$', views.unit_topic_resources, name='unit_topic_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/$', views.view_notes, name='view_notes'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/lessons/$', views.unit_topic_lessons, name='unit_topic_lessons'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/edit/$', views.notes, name='notes'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/history/$', views.notes_history, name='notes_history'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/questions/$', views.questions, name='questions'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/questions/add/$', views.question, name='question'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.unit_topic, name='unit_topic'),
    # url(r'^(?P<slug>[\w\d-]+)/$', views.subject, name='subject'),

    # static pages
    url(r'^about',
    TemplateView.as_view(template_name='uploader/about.html'),
    name='about'),
    url(r'^add-resource', 
    TemplateView.as_view(template_name='uploader/add_resource.html'),
    name='add_resource'),
    url(r'^signup',
    TemplateView.as_view(template_name='uploader/signup.html'),
    name='signup'),

] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

uploader/templates/uploader/groups.html
{% extends 'uploader/base.html' %}
{% load static %}
{% block body_block %}
<h1>{% block head_title %}My Groups{% endblock %}</h1>
{% for group in groups %}
<p>
    <a href="{% url 'uploader:group' group.code %}">
    {{ group.name }} 
    </a>
    
    (<strong>Code:</strong> {{ group.code }})</p>
{% endfor %}
<p>
<a class="btn btn-default" href="{% url 'uploader:groups' %}">
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
	Add group
</a>
</p>
{% endblock %}

uploader/templates/uploader/subject_view.html
{% extends 'uploader/base.html' %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
{% block body_block %}
<ol class="breadcrumb">
    <li><a href="{% url 'uploader:subjects' %}">Home</a></li>
    <li class="active">{{ subject.subject_name }}</li>
</ol>
<h1>{% block head_title %}{{ subject.subject_name }}{% endblock %}</h1>
<img src="{% static 'uploader/img/18x18/subjects/' %}{{ subject.subject_name|slugify }}_large.jpg" />
<h2>Categories</h2>
{% for category in categories %}
<li><a href="{% url 'uploader:category' subject.slug category.slug %}">{{category}}</a></li>
{% endfor %}
{% endblock %}

uploader/templates/uploader/subjects.html
{% extends 'uploader/base.html' %}
{% block body_block %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<h1>{% block head_title %}Subjects{% endblock %}</h1>
    {% if subjects %}
    <div class="row">
        {% for subject in subjects %}
          <div class="col-sm-6 col-md-3">
            <a href="{% url 'uploader:subject' subject.slug %}" class="thumbnail">
              <img src="{{ STATIC_PREFIX }}uploader/img/subjects/{{ subject.slug }}.jpg" alt="{{ subject.slug }}">
            </a>
            <h4 class="text-center">{{ subject.subject_name }}</h3>
          </div>
        {% endfor %}
        </div>
    {% else %}
        <p>Oops, no subjects. This is embarrasing.</p>
    {% endif %}
{% endblock %}

uploader/templates/uploader/syllabus_index.html
{% extends 'uploader/base.html' %}
{% block body_block %}
<ol class="breadcrumb">
    <li><a href="{% url 'uploader:subjects' %}">Home</a></li>
    <li><a href="{% url 'uploader:subject' subject.slug %}">{{ subject.subject_name }}</a></li>
    <li class="active">{{ level.level_name }}</li>
</ol>
<h1>{% block head_title %}{{ subject.subject_name }} Syllabuses{% endblock %}</h1>
<p>I found the following syllabuses:</p>
{% if syllabus_list %}
    <ul>
    {% for syllabus in syllabus_list %}
        <li>
            <a href="{% url 'uploader:syllabus' syllabus.subject.slug level.slug syllabus.slug %}">
                {{ syllabus }}
            </a>
        </li> 
    {% endfor %}
    </ul>
{% else %}
    <p>No syllabuses. Drop us a DM on 
    <a href="https://twitter.com/eduresourc_es">twitter</a> to get your syllabus added.</p>
{% endif %}
{% endblock %}

uploader/templates/uploader/test.html
{% extends 'uploader/base.html' %}
{% block head_title %}{{ unit_topic }} Notes{% endblock %}
{% block body_block %}
{% load static %}
<h1>{% block head_title %}{{ unit_topic }} Test{% endblock %}</h1>
<p>
<a class='btn btn-default' href="{% url 'uploader:test_feedback' unit_topic.slug %}">
    <span class="glyphicon glyphicon-ok" aria-hidden="true" title='Preview'></span>
    Feedback
</a>
</p>
    {% if questions %}
    <div id="questions">
    <form action method="post">
        {% csrf_token %}
        {% for question in questions %}
            <div class='question'>
                <h3>Question {{ forloop.counter }}</h3>
                {{ question.text|linebreaks }}</div>
            <p>
                {% for answer in question.answers %}
                    <input type="radio" name="question{{question.id}}" value="{{ answer.number }}"
                    {% if forloop.first %}
                    checked="checked"
                    {% endif %}
                    > 
                    <label class='answer' for="{{ question.id|add:"-"|add:answer.number }}">{{ answer.text }}</label> 
                    <br />
                {% endfor %}
            </p>
            <hr />
        {% endfor %}
        
        <div class="form-group text-center">
            <button type="submit" class="btn btn-success" onclick="testRadios()">Check answers</button>
        </div>
    </form>
    </div>
    {% else %}
    <div align='center'>
    <p>No questions to complete.</p>
    {% if complete_count > 0%}
    <p><strong>{{ complete_count }}</strong> already taken, choose feedback to see your feedback.</p>
    </div>
    {% endif %}
    {% endif %}
{% endblock %}

uploader/templates/uploader/unit_topic.html
{% extends 'uploader/base.html' %}
{% block body_block %}
{% load static %}
<ol class="breadcrumb">
    <li><a href="{% url 'uploader:subjects' %}">Home</a></li>
    <li><a href="{% url 'uploader:subject' unit_topic.unit.syllabus.subject.slug %}">
        {{ unit_topic.unit.syllabus.subject.subject_name|truncatechars:30 }}</a></li>
    <li><a href="{% url 'uploader:syllabuses' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug %}">
     {{ unit_topic.unit.syllabus.exam_level.level_name|truncatechars:30 }}</a></li>
    <li><a href="{% url 'uploader:syllabus' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug %}"> 
     {{ unit_topic.unit.syllabus|truncatechars:30 }}</a></li>
    <li><a href="{% url 'uploader:unit' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug %}">
     {{ unit_topic.unit.title|truncatechars:30 }}</a></li>
     <li class="active">{{ unit_topic.title|truncatechars:30 }}</li>
</ol>
<h1>{% block head_title %}{{ unit_topic.title }}{% endblock %}</h1>
{% if user.is_authenticated %}
<div class="favourite">
    {% if favourite %}
    <a class='btn btn-primary' href="{% url 'uploader:remove_favourite' 'unit_topic' unit_topic.slug %}">
            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
            Unfavourite
    </a>
    {% else %}
    <a class='btn btn-primary' href="{% url 'uploader:add_favourite' 'unit_topic' unit_topic.slug %}">
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            Favourite
    </a>
    {% endif %}
</div>
{% endif %}
{% if unit_topic.description and unit_topic.description != "" %}
<h2>Description</h2>
<div class="well">
    {{ unit_topic.description|safe }}
</div>
{% endif %}
<h2>Information</h2>
<p>For this unit topic, we have the following:</p>
<table class="small-alignment">
<tbody>
<tr>
    <td>
            
                <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span>
                </td>
    <td>
        <a href="{% url 'uploader:unit_topic_resources' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug %}">
                Resources</a>
    </td>
    <td>
                {% if resources %}<span class="badge">{{ resources }}</span>
                {% else %}<span class="badge">0</span>{% endif %}
                
            
</td></tr>
<tr><td>
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        </td>
    <td>
        <a href="{% url 'uploader:view_notes' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug %}">
        Notes
        </a>
        </td>
    <td>
        {% if notes %}<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>{% else %}<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>{% endif %}
</td></tr>
{% if user.teacherprofile %}
<tr><td>
        <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>
        </td>
    <td>
    <a href="{% url 'uploader:unit_topic_lessons' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug %}">
        Lessons
        </td>
    <td>
        {% if lessons %}<span class="badge">{{ lessons }}</span>
        {% else %}<span class="badge">0</span>{% endif %}
</td></tr>
<tr><td>
        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>  
        </td>
    <td>
        <a href="{% url 'uploader:questions' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug %}">
        Questions
        </a>
        </td>
    <td>
        {% if questions %}<span class="badge">{{ questions }}</span>
        {% else %}<span class="badge">0</span>{% endif %}
    </a>
</td></tr>
</tbody>
</table>
{% endif %}
{% if related_topics %}
    <h2>Related Unit Topics</h2>
    <p>You might also want to check other similar unit topics for resources.</p>
    <ul>
    {% for related in related_topics %}
    <li>
    {% if related.unit_topic_1 == unit_topic %}
        <a href="{% url 'uploader:unit_topic' related.unit_topic_2.unit.syllabus.subject.slug related.unit_topic_2.unit.syllabus.exam_level.slug related.unit_topic_2.unit.syllabus.slug related.unit_topic_2.unit.slug related.unit_topic_2.slug %}">
        {{ related.unit_topic_2.unit.syllabus }} > {{ related.unit_topic_2 }}
        </a>
    {% else %}
        <a href="{% url 'uploader:unit_topic' related.unit_topic_1.unit.syllabus.subject.slug related.unit_topic_1.unit.syllabus.exam_level.slug related.unit_topic_1.unit.syllabus.slug related.unit_topic_1.unit.slug related.unit_topic_1.slug %}">
        {{ related.unit_topic_1.unit.syllabus }} > {{ related.unit_topic_1 }} 
        </a>
    </li>
    {% endif %}
    {% endfor %}
    </ul>
{% endif %}
{% endblock %}

uploader/templates/uploader/unit_topic_questions.html
{% extends 'uploader/base.html' %}
{% block head_title %}{{ unit_topic }} Notes{% endblock %}
{% block body_block %}
{% load static %}
<ol class="breadcrumb">
    <li><a href="{% url 'uploader:subjects' %}">Home</a> </li>
    <li><a href="{% url 'uploader:subject' unit_topic.unit.syllabus.subject.slug %}">
        {{ unit_topic.unit.syllabus.subject.subject_name|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:syllabuses' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug %}">
     {{ unit_topic.unit.syllabus.exam_level.level_name|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:syllabus' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug %}"> 
     {{ unit_topic.unit.syllabus|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:unit' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug %}">
     {{ unit_topic.unit.title|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:unit_topic' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug  %}">
     {{ unit_topic.title|truncatechars:25 }}</a></li>
    <li class='active'>{% if request.user.studentprofile %}Test{% else %}Questions{% endif %}</li>
</ol>
    <h1>Questions</h1>
    {% include 'uploader/unit_topic_tabs.html' %}
    <p>
        <a href="{% url 'uploader:question' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug %}">
            <button class='btn btn-success'>
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true" title='Add question'></span>
                Add Question</button>
        </a>    
    </p>
    {% if questions %}
        {% for question in questions %}
            <p><strong>{{ question.text }}</strong>
            <ul>
                {% for answer in question.answers %}
                    <li>{{ answer.text }}</li>
                {% endfor %}
            </ul>
            </p>
        {% endfor %}
    {% else %}
    <p>No questions</p>
    {% endif %}
{% endblock %}

uploader/templates/uploader/unit_topic_resources.html
{% extends 'uploader/base.html' %}
{% load tags %}
{% block body_block %}
<ol class="breadcrumb">
    <li><a href="{% url 'uploader:subjects' %}">Home</a></li>
    <li><a href="{% url 'uploader:subject' unit_topic.unit.syllabus.subject.slug %}">
        {{ unit_topic.unit.syllabus.subject.subject_name|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:syllabuses' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug %}">
     {{ unit_topic.unit.syllabus.exam_level.level_name|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:syllabus' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug %}"> 
     {{ unit_topic.unit.syllabus|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:unit' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug %}">
     {{ unit_topic.unit.title|truncatechars:25 }}</a></li>
    <li><a href="{% url 'uploader:unit_topic' unit_topic.unit.syllabus.subject.slug unit_topic.unit.syllabus.exam_level.slug unit_topic.unit.syllabus.slug unit_topic.unit.slug unit_topic.slug  %}">
     {{ unit_topic.title|truncatechars:25 }}</a></li>
    <li class='active'>Resources</li>
</ol>
<h1>{% block head_title %}{{ unit_topic.title }} Resources{% endblock %}</h1>
{% include 'uploader/unit_topic_tabs.html' %}

{% resources_table resources %}
{% endblock %}