openteach/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from openteach import settings
from uploader import views

#if not settings.DEBUG:
#from haystack.forms import HighlightedSearchForm
#from haystack.views import SearchView

urlpatterns = [
	#url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('uploader.urls', namespace="uploader")),
    #url(r'^uploader/', include('uploader.urls', namespace="uploader")),
    #url(r'^$', views.index, name='index'),
]

#if not settings.DEBUG:
#additional_patterns = patterns(
#    url(r'^search/$', SearchView(form_class=HighlightedSearchForm)),
#)
#urlpatterns += additional_patterns 

uploader/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from uploader import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^denied/$', views.denied, name='denied'),
 
    url(r'^assignment/add/$', views.assignment, name='assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/$', views.view_assignment, name='view_assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/edit/$', views.assignment, name='assignment'),
    url(r'^assignment/(?P<code>[\w\d]+)/delete/$', views.delete_assignment, name='delete_assignment'),
    url(r'^assignment/(?P<assignment_code>[\w\d-]+)/mark/(?P<submission_id>[\d]+)/$', views.mark_assignment, name='mark_assignment'),
    url(r'^assignment/(?P<assignment_code>[\w\d-]+)/mark/(?P<absent>[\w]+)/(?P<student_id>[\d]+)', views.mark_assignment, name='mark_assignment'),
    
    url(r'^lookup/syllabus/(?P<subject_id>\d+)/$', views.get_syllabuses, name='get_syllabuses'),
    url(r'^lookup/unit/(?P<syllabus_id>\d+)/$', views.get_units, name='get_units'),
    url(r'^lookup/quick/(?P<type>[\w]+)/(?P<code>[\w\d]+)/$', views.get_object_from_code, name='get_object_from_code'),
    url(r'^lookup/unit_topic/(?P<unit_id>\d+)/$', views.get_unit_topics, name='get_unit_topics'),
    url(r'^lookup/url_description/$', views.get_url_description, name='get_url_description'),
    url(r'^bulk/bookmark/(?P<action>.+)/(?P<ids>.+)/$', views.bulk_bookmark_update, name='bulk_bookmark_update'),
    url(r'^pre-post/(?P<action>.+)/(?P<id>.+)/$', views.pre_post, name='pre_post'),
    
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^favourites/$', views.favourites, name='favourites'),
    url(r'^favourites/add-(?P<thing>[\w\d-]+)/(?P<slug>[\w\d-]+)$', views.add_favourite, name='add_favourite'),
    url(r'^favourites/remove-(?P<thing>[\w\d-]+)/(?P<slug>[\w\d-]+)$', views.remove_favourite, name='remove_favourite'),
    
    url(r'^resource/(?P<slug>[\w\d-]+)/$', views.view_resource, name='view_resource'),
    url(r'^resource/(?P<slug>[\w\d-]+)/embed/$', views.view_resource_embed, name='view_resource_embed'),
    url(r'^resource/(?P<slug>[\w\d-]+)/delete$', views.delete_resource, name='delete_resource'),
    url(r'^lesson/(?P<code>[\w\d-]+)/edit', views.edit_lesson, name='edit_lesson'),
    url(r'^lesson/(?P<code>[\w\d-]+)/delete', views.delete_lesson, name='delete_lesson'),
    url(r'^lesson/(?P<code>[\w\d-]+)/link', views.link_lesson, name='link_lesson'),
    url(r'^lesson/new/$', views.lesson_creator, name='lesson_creator'),
    url(r'^lesson_item/(?P<id>[\d-]+)/edit', views.edit_lesson_item, name='edit_lesson_item'),
    #url(r'^resource/(?P<slug>[\w\d-]+)/edit$', views.resource, name='resource'),
    
    url(r'^groups/$', views.groups_list, name='groups_list'),
    url(r'^groups/add/$', views.groups, name='groups'),
    url(r'^groups/(?P<slug>[\w\d-]+)/edit/$', views.groups, name='groups'),
    url(r'^group/(?P<slug>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/$', views.lesson, name='lesson'),
    url(r'^group/(?P<code>[\w\d-]+)/$', views.group, name='group'),
    url(r'^group/(?P<group_code>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/show/$', views.lesson_show, name='lesson_show'),
    url(r'^group/(?P<group_code>[\w\d-]+)/lesson/(?P<code>[\w\d-]+)/present/$', views.lesson_present, name='lesson_present'),
    
    # url(r'^bookmark/add/(?P<url>[-_./\w\d-]+)$', views.bookmark, name='bookmark'),
    url(r'^bookmark/add/', views.bookmark, name='bookmark'),
    url(r'^bookmark/link/(?P<slug>[\w\d-]+)/$', views.link_bookmark, name='link_bookmark'),
    # url(r'^bookmark/add/stage_two/$', views.link_resource, name='link_resource'),
    url(r'^bookmark/(?P<slug>[\w\d-]+)/edit/$', views.bookmark, name='bookmark'),
    url(r'^bookmark/(?P<slug>[\w\d-]+)/delete/$', views.delete_bookmark, name='delete_bookmark'),

    url(r'^file/add/$', views.file, name='file'),
    url(r'^file/add/stage_two/$', views.link_resource, name='link_resource'),
    url(r'^file/link/(?P<slug>[\w\d-]+)/$', views.link_file, name='link_file'),
    url(r'^file/(?P<slug>[\w\d-]+)/edit/$', views.file, name='file'),
    url(r'^file/(?P<slug>[\w\d-]+)/delete/$', views.delete_file, name='delete_file'),
    
    url(r'^user/profile/$', views.profile, name='profile'),
    url(r'^user/resources', views.user_resources, name='user_resources'),
    url(r'^user/files', views.user_files, name='user_files'),
    url(r'^user/bookmarks', views.user_bookmarks, name='user_bookmarks'),
    url(r'^user/questions', views.user_questions, name='user_questions'),
    url(r'^user/lessons', views.user_lessons, name='user_lessons'),
    url(r'^user/grading/add/', views.grading, name='grading'),
    url(r'^user/grading/', views.user_grading, name='user_grading'),
    url(r'^user/tests/', views.user_tests, name='user_tests'),
    url(r'^user/(?P<username>[\w\d-]+)/$', views.profile, name='profile'),
    
    url(r'lesson/(?P<slug>[\w\d-]+)/$', views.lesson, name='lesson'),

    
    url(r'^notes/(?P<code>[\w\d-]+)/$', views.view_notes_code, name='view_notes_code'),
    # url(r'^notes/(?P<slug>[\w\d-]+)/edit/$', views.notes_d, name='notes_d'),
    
    url(r'^students/signup/$', views.student_signup, name='student_signup'),
    url(r'^teachers/signup/$', views.teacher_signup, name='teacher_signup'),

    
    # url(r'^leaderboard', views.leaderboard, name='leaderboard'),
    
    url(r'^vote/(?P<content_type>[\w]+)/(?P<object_id>[\d]+)/(?P<vote>[\d])/$', views.vote, name='vote'),
    
    url(r'^licences', views.licences, name='licences'),
    
    url(r'^upload_image', views.upload_image, name='upload_image'),
    url(r'^image/(?P<image_id>\d+)/$', views.view_image, name='view_image'),
    
    url(r'^test/add', views.add_test, name='add_test'),
    url(r'^test/(?P<code>[\w\d-]+)/feedback', views.test_feedback, name='test_feedback'),
    url(r'^test/(?P<code>[\w\d-]+)/link', views.link_test, name='link_test'),
    url(r'^test/(?P<code>[\w\d-]+)', views.test, name='test'),

    
    url(r'^add-question/(?P<slug>[\w\d-]+)', views.question, name='question'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/resources$', views.topic_resources, name='topic_resources'),
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)$', views.topic, name='topic'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/$', views.category, name='category'),
    url(r'^(?P<subject_slug>[\w\d-]+)/$', views.subject, name='subject'),
    
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/notes/$', views.view_notes, name='view_notes'),
    url(r'^(?P<subject_slug>[\w\d-]+)/(?P<category_slug>[\w\d-]+)/(?P<topic_slug>[\w\d-]+)/notes/edit$', views.notes, name='notes'),

    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.syllabus, name='syllabus'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/resources/$', views.syllabus_resources, name='syllabus_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/$', views.syllabuses, name='syllabuses'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.unit, name='unit'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/resources/$', views.unit_resources, name='unit_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/resources/$', views.unit_topic_resources, name='unit_topic_resources'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/$', views.view_notes, name='view_notes'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/lessons/$', views.unit_topic_lessons, name='unit_topic_lessons'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/edit/$', views.notes, name='notes'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/notes/history/$', views.notes_history, name='notes_history'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/questions/$', views.questions, name='questions'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/questions/add/$', views.question, name='question'),
    # url(r'^(?P<subject_slug>[\w\d-]+)/(?P<exam_slug>[\w\d-]+)/(?P<syllabus_slug>[\w\d-]+)/(?P<unit_slug>[\w\d-]+)/(?P<slug>[\w\d-]+)/$', views.unit_topic, name='unit_topic'),
    # url(r'^(?P<slug>[\w\d-]+)/$', views.subject, name='subject'),

    # static pages
    url(r'^about',
    TemplateView.as_view(template_name='uploader/about.html'),
    name='about'),
    url(r'^add-resource', 
    TemplateView.as_view(template_name='uploader/add_resource.html'),
    name='add_resource'),
    url(r'^signup',
    TemplateView.as_view(template_name='uploader/signup.html'),
    name='signup'),

] 

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

uploader/templates/uploader/snippets/assignment_table.html
{% if assignments %}
<div class='table-responsive'>
<table class='table table-striped table-condensed'>
    <tr>
        <th>Assignment</th>
        {% if not group and teacher_or_student == 'teacher' %}
            <th>Group</th>
            <!--<th>Set</th>-->
        {% elif teacher_or_student == 'student' %}
            <th>Class</th>
        {% endif %}
        <th>Deadline</th>
        
        {% if teacher_or_student == 'student' %}
            <th>Status</th>
        {% endif %}
            <th></th>
        
        {% for assignment in assignments %}
            {% if teacher_or_student == 'teacher' %}
            <tr>
                <td>
                <a href="{% url 'uploader:view_assignment' assignment.code %}">{{ assignment.title }}</a>
                </td>
                {% if not group %}
                    <td>{{ assignment.group }}</td>
                {% endif %}
                <td>{{ assignment.deadline }}</td>
                <!--<td>{{ assignment.pub_date }}</td>-->
                    <td align='right'>
                        <a href="{% url 'uploader:assignment' assignment.code %}" class='btn btn-xs btn-default'>
                            <span style="font-size: 0.9em" class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            Edit
                        </a>
                        <a href="{% url 'uploader:delete_assignment' assignment.code %}" class='btn btn-xs btn-danger' onclick="javascript:return confirm('DELETE this assignment? All student work will be deleted too')">
                            <span style="font-size: 0.9em" class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Delete
                        </a>
                    </td>
            {% else %}
                {% if assignment.get_status_display == 'Marked' %}
                <tr class='success'>
                {% elif assignment.get_status_display == 'Not Marked' %}
                <tr>
                {% else %}
                <tr class='danger'>
                {% endif %}
                <td>{{ assignment.assignment.title }}</td>
                <td>{{ assignment.assignment.group }}</td>
                <td>{{ assignment.assignment.deadline }}</td>
                <td>{{ assignment.get_status_display }}</td>
                <td>
                    <a class='btn btn-default btn-xs' href="{% url 'uploader:view_assignment' assignment.assignment.code %}">
                        View feedback
                    </a>
                </td>
            {% endif %}
            </tr>

        {% endfor %}
    </tr>
</table>
</div>
{% else %}
<p>No assignments.</p>
{% endif %}

uploader/templates/uploader/snippets/lesson_table.html
{% load tags %}
{% if lessons %}
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
<p>Clicking <strong>present</strong> will show you a large screen version of 
the lesson you can display on your board.</p>
<div class='table-responsive'>
<table class='table table-striped table-condensed'>
    <th>Lesson</th>
    {% if not group %}<th>Group</th>{% endif %}
    <th>Unit Topic</th>
    <th>Short link</th>
    <th>Date</th>
    <th>Feedback <span class="glyphicon glyphicon-question-sign" style="font-size: 0.9em" aria-hidden="true" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Average post-lesson understanding (of out 5)"></span></th>
    <th></th>
    
{% for lesson in lessons %}
<tr>
    <td>{{ lesson.lesson.title }}</td>
    {% if not group %}<td>{{ lesson.group }}</td>{% endif %}
    <td>
        {{ lesson.lesson.unit_topic }}
    </td>
    <td>
        {{ lesson.link|urlize }}
    </td>
    <td>
        {% if lesson.date %}
        {{ lesson.date|date:"D dS M" }} 
            {% if lesson.period %}P{{ lesson.period }}{% endif %}
        {% endif %}
        </td>
    {% if lesson.feedback and lesson.feedback < 4 %}
      <td class="danger text-center">{{ lesson.feedback|floatformat:"1" }}
    {% elif lesson.feedback and lesson.feedback >= 3 and lesson.feedback < 4 %}
      <td class="warning text-center">{{ lesson.feedback|floatformat:"1" }}
    {% elif lesson.feedback and lesson.feedback >= 4 %}
        <td class="success text-center">{{ lesson.feedback|floatformat:"1" }}
    {% else %}
        <td>
    {% endif %}
    </td>
    <td align='right'>
                 <a class='btn btn-default btn-xs' href="{% url 'uploader:lesson' lesson.group.code lesson.lesson.code %}">
                    <span style="font-size:100%" class="glyphicon glyphicon-modal-window" aria-hidden="true"></span>
                    View
                    </a>
                    <a class='btn btn-default btn-xs' href="{% url 'uploader:lesson_show' lesson.group.code lesson.lesson.code %}">
                    <span style="font-size:100%" class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>
                    Present</a>
    </td>
</tr>
{% endfor %}
</table>
</div>
{% else %}
<p>No lessons</p>
{% endif %}

uploader/templates/uploader/snippets/linking_embed.html
<div id="link_form">
<div class="subject">
        
        <label for="id_subject">Subject</label>
            <span class="label label-danger">required</span>
        <select class=" form-control" id="id_subject" name="subject">
            <option>---------</option>
            {% for subject in subjects %}
            <option value="{{ subject.id}}">{{ subject }}</option>
            {% endfor %}
</select>
    </div>
    
    <div class="syllabus">
        
        <label for="id_syllabus">Syllabus</label>
            <span class="label label-danger">required</span>
        <select class=" form-control" id="id_syllabus" name="syllabus">

</select>
    </div>
    
    <div class="unit">
        
        <label for="id_unit">Unit</label>
        
        <select class=" form-control" id="id_unit" name="unit">
    </select>
    </div>

    <div class="unit_topic">
        
        <label for="id_unit_topic">Unit Topic</label>
        
        <select class=" form-control" id="id_unit_topic" name="unit_topic">
        </select>
    </div>
</div>
</div>

uploader/templates/uploader/snippets/resources_table.html
{% if resources %}
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
<div class='table-responsive'>
<table class='table table-striped table-condensed'>
    <thead>
        <th class='text-center'>Type</th>
        <th class='text-center'>Title</th>
        <th class='text-center'>Rating</th>
        <th class='text-center'>Description</th>
    </thead>
    <tbody>
{% for resource in resources %}
    <tr>
    {% if resource.bookmark %}
        <td align='center'>
        {% if resource.bookmark.type == 'video' %}
        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Video"></span>
        {% elif resource.bookmark.type == 'news' %}
        <span class="glyphicon glyphicon-list-alt" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="News article"></span>
        {% elif resource.bookmark.type == 'image' %}
        <span class="glyphicon glyphicon-image" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Image"></span>
        {% elif resource.bookmark.type == 'info' %}
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Informational source"></span>
        {% elif resource.bookmark.type == 'blog' %}
        <span class="glyphicon glyphicon-comment" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Blog article or site"></span>
        {% else %}
        <span class="glyphicon glyphicon-bookmark" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Website"></span>
        {% endif %}
        </td>
        <td>
            {% if resource.bookmark %}
        <a href="{% url 'uploader:view_resource' resource.bookmark.slug|slugify %}">{{ resource.bookmark }}</a>
        {% else %}

       <a href="{% url 'uploader:view_resource' resource.file.slug|slugify %}">{{ resource.bookmark }}</a>
       {% endif %}
        </td>
        <td align='center'>{{ resource.rating }}</td>
        <td>
         {{ resource.bookmark.description|truncatewords:20 }} 
         <!--{% if resource.avg_rating %}-->
         <!--    ({{ resource.avg_rating }})-->
         <!--{% endif %}-->
         </td>
    {% else %}
    <td align='center'>
        <span class="glyphicon glyphicon-paperclip" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="File"></span>
    </td>
    <td>
        <a href="{% url 'uploader:view_resource' resource|slugify %}">{{ resource }}</a>
    </td>
    <td align='center'>{{ resource.rating }}</td>
    <td>
        {{ resource.file.description|truncatewords:20 }}
    </td>
    {% endif %}
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% else %}
No resources :( <a href="{% url 'uploader:add_resource' %}">Add some?</a>
{% endif %}

uploader/templates/uploader/snippets/test_table.html
{% if tests %}
<div class='table-responsive'>
<table class='table table-striped table-condensed'>
    <tr>
        <th>Test</th>
        {% if not group %}<th>Group</th>{% endif %}
        <!--<th>Status</th>-->
        <th>Set</th>
        <th>Deadline</th>
        <!--<th></th>-->
        {% for test in tests %}
        <tr>
            <td>{{ test }}</td>
            {% if not group %}<td>{{ test.group }}</td>{% endif %}
            <!--<td></td>-->
            <td>{{ test.pub_date }}</td>
            <td>{{ test.deadline }}</td>
            <!--{% if teacher_or_student == 'teacher' %}-->
            <!--<td><a href="" class='btn btn-default'>View Test</a></td>-->
            <!--{% else %}-->
            <!--<td>student</td>-->
            <!--{% endif %}-->
        </tr>
        {% endfor %}
    </tr>
</table>
</div>
{% else %}
    <p>No tests</p>
{% endif %}